server:
  port: 8092

spring:
  application:
    name: credit-feign

logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

feign.hystrix.enabled: false
