server:
  servlet:
    context-path: /credit
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

feign.hystrix.enabled: false

spring:
  application:
    name: credit
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
  file:
    name: /home/hank/logs/service/out.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

common:
  database:
    ip: localhost
    port: 3306