server:
  servlet:
    context-path: /service
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

feign.hystrix.enabled: false

spring:
  application:
    name: credit
  jackson:
    property-naming-strategy: SNAKE_CASE
  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
    # Redis服务器地址
    host: localhost
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password:
#    # 连接超时时间（毫秒）
#    timeout: 1000
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 20
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0


logging:
  level:
    root: info
  file:
    name: /home/hank/logs/service/out.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

common:
  database:
    ip: localhost
    port: 3306

system:
  anonymous:
    path: /anony/**,/user/auth/**