server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    renewalPercentThreshold: 0.45

logging:
  level:
    root: info

feign.hystrix.enabled: false
